version: '3.3'

services:
  rgee:
    image: csaybar/rgee
    volumes:      
      - $HOME/.config/earthengine/ndef:/home/rgee/.config/earthengine/ndef
    environment:
      - USER=rgee
      - PASSWORD=rgee
    ports:
      - "8787:8787"